matrix:
  include:

  - language: php
    php:
    - 7.2
    - 7.1
    - 7.0
    - 5.6
    install:
    - composer install
    script:
    - cd ${TRAVIS_BUILD_DIR}
    - composer run-script test

  - language: python
    python:
    - 3.5
    install:
    - pip install flake8
    script:
    - cd ${TRAVIS_BUILD_DIR}
    - flake8 .

  - language: markdown
    script:
    - gem install mdl
    - cd ${TRAVIS_BUILD_DIR}
    - mdl -s markdownlint.rb *.md docs/fr_FR/*.md