---
langs: [fr_FR]
baseurl: "/"
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
permalink: /404.html
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
 - jekyll-paginate
 - jekyll-seo-tag
exclude:
 - vendor
plugins:
 - jekyll-seo-tag
title: "Documentation plugin ZiGate"
description: "Ceci est la documentation, liée au plugin ZiGate pour Jeedom."
author: "Jeedom-Zigate teams"
image: https://www.jeedom.com/site/logo.png
social:
  name:  Jeedom-Zigate
  links:
    - https://github.com/Jeedom-Zigate